/*
 * gauntlet_report.mjs — B316 P3's committed summary: reads a gauntlet run from
 * local/patchspace/<run>/ and writes a markdown report (no raw audio, no patch dumps
 * beyond the few worst indices, which re-derive from the seed). HYPERSAW, 2026-09-27,
 * ROADMAP B316. Invoked as `node tools/patchspace/gauntlet_report.mjs --run NAME [--out F]`
 * (its own entry point: gauntlet.mjs cannot import it under top-level await without a cycle).
 *
 * Every rate is printed beside its PROVISIONAL threshold (gauntlet.mjs THRESH): metrics are
 * measured, not gates. Hotspots are LIFTS: the failure rate inside a parameter bin (an enum
 * option, a toggle, or a quintile of taper position — the sampler's own space) over the
 * rate in the whole run; a bin needs n >= 25 to be listed. The report re-measures a sample
 * of patches in this process and compares every non-CPU field bit for bit (determinism).
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { loadavg, cpus } from 'node:os';
import { ROOT, loadSpace, posOf, evalCond, readRepo } from './space.mjs';
import { samplePatch, measure, failures, incoherence, labels, THRESH, readRun } from './gauntlet.mjs';
import { asEvalTree, hash32 } from './gen_dependency_tree.mjs';

const arg = (n, d) => { const i = process.argv.indexOf('--' + n); return i > 0 ? process.argv[i + 1] : d; };
const pct = (a, q) => { if (!a.length) return null; const s = a.slice().sort((x, y) => x - y); return s[Math.min(s.length - 1, Math.floor(q * s.length))]; };
const f = (x, d) => (x === null || x === undefined || Number.isNaN(x) ? '—' : typeof x === 'number' ? x.toFixed(d === undefined ? 3 : d) : String(x));
const rate = (n, d) => (d ? (100 * n / d).toFixed(1) + '%' : '—');
const CLASSES = ['nonfinite', 'silent', 'overload6', 'overloadVoice', 'alias', 'clicks', 'dc'];
const INCO = ['rootAbsent'];
/* B360: noisy/rough are LABELS — measured and reported, but no longer reduce healthy or coherent yield */
const LABELS = ['noisy', 'rough'];

export async function report() {
  const run = arg('run', 'default');
  const out = arg('out', `docs/patchspace/gauntlet-${run}.md`);
  const { rows, meta } = readRun(run);
  if (!meta) throw new Error(`no run "${run}" under local/patchspace (meta.json missing)`);
  const { params } = loadSpace(), T = asEvalTree(JSON.parse(readRepo('tools/patchspace/dependency_tree.json')));
  const all = [...rows.values()].filter(r => r.i < (r.mode === 'edge' ? meta.edge : meta.broad)).sort((a, b) => (a.mode === b.mode ? a.i - b.i : a.mode < b.mode ? -1 : 1));
  for (const r of all) {
    const s = samplePatch(meta.seed, r.i, r.mode);
    r.P = s.patch;
    r.fail = failures(r); r.inco = incoherence(r); r.labels = labels(r);   // B360: recomputed live, same as fail/inco (not trusted from disk)
    r.b1 = evalCond({ pred: 'B1' }, r.P, T.predicates); r.b2 = evalCond({ pred: 'B2' }, r.P, T.predicates);
    r.blades = (r.b1 ? 1 : 0) + (r.b2 ? 1 : 0);
  }
  const L = [];
  const P = s => L.push(s);
  const byMode = m => all.filter(r => r.mode === m);
  const modes = ['broad', 'edge'].filter(m => byMode(m).length);

  /* determinism: re-measure a sample here and compare every non-CPU field */
  const sample = all.filter((_, k) => k % Math.max(1, Math.floor(all.length / 6)) === 0).slice(0, 6);
  let detOk = 0; const detBad = [];
  for (const r of sample) {
    const m = measure(r.P, hash32(meta.seed, r.i, 77), { conv: all.some(x => x.aliasConvClass) });
    const bad = Object.keys(m).filter(k => !/^cpu/.test(k) && JSON.stringify(m[k]) !== JSON.stringify(r[k]));
    if (bad.length) detBad.push(`${r.mode}#${r.i}: ${bad.join(',')}`); else detOk++;
  }

  P(`# B316 P3 — patch-space gauntlet: run \`${run}\``);
  P('');
  if (arg('note')) { P(`> ${arg('note')}`); P(''); }
  P(`Generated by \`node tools/patchspace/gauntlet_report.mjs --run ${run}\` (HYPERSAW, B316 P3, records PR #810). ` +
    'The engine is the composed SCALPEL × horde engine (`docs/design/scalpel-horde-engine.js`) in headless Node at 48 kHz. ' +
    '**Every metric is MEASURED, not a gate; every threshold below is PROVISIONAL** until the human\'s blind listening pass calibrates it.');
  P('');
  P('## Run');
  P('');
  P(`| seed | broad | edge | measured | workers | wall | CPU reference (quiet, defaults) |`);
  P(`|---|---|---|---|---|---|---|`);
  P(`| 0x${(meta.seed >>> 0).toString(16)} | ${meta.broad} | ${meta.edge} | ${all.length} | ${meta.workers} | ${(meta.wall / 60).toFixed(1)} min | ${(meta.quietRef * 100).toFixed(1)}% RT per voice |`);
  P('');
  P(`Sampler: taper-space draws, one substream per parameter, then the dependency tree (\`tools/patchspace/dependency_tree.json\`) as a fixpoint — inactive parameters sit at their defaults. ` +
    `Median live parameters per patch: broad ${f(pct(byMode('broad').map(r => r.live), 0.5), 0)}, edge ${f(pct(byMode('edge').map(r => r.live), 0.5), 0)} of ${params.length}; ` +
    `unsettled fixpoints: ${all.filter(r => !r.settled).length}.`);
  P('');
  P(`Determinism: ${detOk} of ${sample.length} patches re-measured in the report process reproduce every non-CPU field exactly${detBad.length ? '; MISMATCH: ' + detBad.join('; ') : ''}.`);
  P('');
  P('## Thresholds (provisional)');
  P('');
  P('| class | rule |');
  P('|---|---|');
  P('| nonfinite | any NaN/±Inf sample in any segment |');
  P('| silent | TONAL window RMS < -90 dBFS |');
  P(`| overload6 | 6 × cpuVoiceNorm > ${THRESH.overloadPoly6} (the lab's 6-voice pool over real time) |`);
  P(`| overloadVoice | cpuVoiceNorm > ${THRESH.overloadVoice} (one voice over real time) |`);
  P(`| alias | aliasConvDb > ${THRESH.aliasConvDb} dB (B351: the os-convergence estimator, the patch at 1×..16× its oversampling; aliasDb, vs the 4×-oversampled reference, is a measured column above; see the caveat in gauntlet.mjs) |`);
  P(`| clicks | > ${THRESH.clicks} click frames in the TONAL window (20 dB over the median HF frame) |`);
  P(`| dc | dcRatio > ${THRESH.dcRatio} |`);
  P(`| rootAbsent (coherence) | rootPresence < ${THRESH.rootPresence} |`);
  P(`| noisy (LABEL, B360 — does not reduce healthy or coherent yield) | noiseDb > ${THRESH.noiseDb} dB (B350: moved off flatness, still a measured column above) |`);
  P(`| rough (LABEL, B360 — does not reduce healthy or coherent yield) | roughness > ${THRESH.roughness} (two pure tones a minor second apart read 0.090) |`);
  P('');
  P('## Yield');
  P('');
  P('B360 (human, 2026-09-29: "I think noisy and rough should just label; some patches want noisy or rough"): ' +
    '`noisy` and `rough` below are LABELS, not failure or coherence classes — they tag a patch that P4 can target ' +
    'or avoid, and no longer reduce `healthy` or `coherent`. `healthy` is unchanged by B360 (noisy/rough never gated ' +
    'it); `coherent` rises because it no longer also requires `!noisy && !rough`.');
  P('');
  P('| mode | n | healthy (no failure class) | coherent (healthy + no coherence flag) | ' + CLASSES.join(' | ') + ' | ' + INCO.join(' | ') + ' | ' + LABELS.join(' | ') + ' |');
  P('|---|---|---|---|' + CLASSES.map(() => '---').join('|') + '|' + INCO.map(() => '---').join('|') + '|' + LABELS.map(() => '---').join('|') + '|');
  for (const m of modes) {
    const R = byMode(m), n = R.length;
    P(`| ${m} | ${n} | ${rate(R.filter(r => !r.fail.length).length, n)} | ${rate(R.filter(r => !r.fail.length && !r.inco.length).length, n)} | ` +
      CLASSES.map(c => rate(R.filter(r => r.fail.includes(c)).length, n)).join(' | ') + ' | ' + INCO.map(c => rate(R.filter(r => r.inco.includes(c)).length, n)).join(' | ') +
      ' | ' + LABELS.map(c => rate(R.filter(r => r.labels.includes(c)).length, n)).join(' | ') + ' |');
  }
  P('');
  P('## Metric distributions (p5 / p25 / p50 / p75 / p95)');
  P('');
  const MET = [['rmsDb', 1], ['lufs', 1], ['crestDb', 1], ['dcRatio', 4], ['flatness', 4], ['noiseDb', 1], ['rootPresence', 3], ['roughness', 4], ['aliasDb', 1],
    ['aliasConvDb', 1], ['aliasFoldDb', 1], ['aliasDynDb', 1], ['decimLeakDb', 1], ['tanhFoldDb', 1], ['aliasTotalDb', 1],
    ['clicks', 0], ['clicksC', 0], ['peakC', 3], ['cpuVoice', 3], ['cpuVoiceNorm', 3], ['cpuPoly', 3]];
  P('| metric | ' + modes.map(m => m + ' p5 / p25 / p50 / p75 / p95').join(' | ') + ' |');
  P('|---|' + modes.map(() => '---').join('|') + '|');
  for (const [k, d] of MET) P(`| ${k} | ` + modes.map(m => { const v = byMode(m).map(r => r[k]).filter(x => typeof x === 'number' && Number.isFinite(x)); return [0.05, 0.25, 0.5, 0.75, 0.95].map(q => f(pct(v, q), d)).join(' / '); }).join(' | ') + ' |');
  P('');
  P('CPU is NOISY (workers share the machine): `cpuVoice` is the raw per-voice real-time fraction; `cpuVoiceNorm` rescales it by a reference patch re-timed in the same worker every 8 patches; `cpuPoly` is the POLY segment\'s whole load (up to four voices plus tails). Rankings hold; absolute numbers carry this Mac.');
  P('');

  /* ---- B346: the aliasing re-read by the os-convergence estimator (beside aliasDb; since B351 the `alias` class reads aliasConvDb) */
  if (all.some(r => r.aliasConvClass)) {
    P('## Aliasing re-read: the os-convergence estimator (B346)');
    P('');
    P('`aliasDb` (B345\'s fixed metric, a measured column) against `aliasConvDb` (what the `alias` class above reads since B351), the os-convergence estimator on the same E5 note and window ' +
      '(`tools/patchspace/metrics.mjs` aliasConvergence: the patch at 1×, 2×, 4×, 8× and 16× its oversampling; per region, the power the test has beyond both finer ' +
      'renders where they are one realisation, or per bin beyond both where they are not; classed by whether it converges AND whether the finer renders\' content ' +
      'above the test\'s Nyquist predicts it). `decimLeakDb` and `tanhFoldDb` are the output stage every os shares (the engine\'s decimator and its output-rate tanh), ' +
      `which neither metric can see, taken at the patch's own os (2× for os 1); \`aliasTotalDb\` is everything the patch at its os has that its oversampled truth ` +
      `(8× and 16×, the tanh at the internal rate, an ideal decimator) lacks. The alias gate's cut, ${THRESH.aliasConvDb} dB, is applied to all of them for comparison only.`);
    P('');
    P('| mode | n | clean | folding | dynamics | aliasDb over the cut | aliasConvDb over the cut | both | aliasConvDb only | aliasDb only | decimLeakDb over the cut | tanhFoldDb over the cut | aliasTotalDb over the cut |');
    P('|---|---|---|---|---|---|---|---|---|---|---|---|---|');
    for (const m of modes) {
      const R = byMode(m), n = R.length, o = r => r.aliasDb > THRESH.aliasConvDb, c = r => r.aliasConvDb > THRESH.aliasConvDb;
      P(`| ${m} | ${n} | ${rate(R.filter(r => r.aliasConvClass === 'clean').length, n)} | ${rate(R.filter(r => r.aliasConvClass === 'folding').length, n)} | ${rate(R.filter(r => r.aliasConvClass === 'dynamics').length, n)} | ` +
        `${rate(R.filter(o).length, n)} | ${rate(R.filter(c).length, n)} | ${rate(R.filter(r => o(r) && c(r)).length, n)} | ${rate(R.filter(r => c(r) && !o(r)).length, n)} | ${rate(R.filter(r => o(r) && !c(r)).length, n)} | ` +
        `${rate(R.filter(r => r.decimLeakDb > THRESH.aliasConvDb).length, n)} | ${rate(R.filter(r => r.tanhFoldDb > THRESH.aliasConvDb).length, n)} | ${rate(R.filter(r => r.aliasTotalDb > THRESH.aliasConvDb).length, n)} |`);
    }
    P('');
    const med = (R, k) => f(pct(R.map(r => r[k]), 0.5), 1);
    P('Median `aliasDb` / `aliasConvDb` by oversampling and band-limiting (all modes):');
    P('');
    P('| os | aa | n | median aliasDb | median aliasConvDb | folding | dynamics |');
    P('|---|---|---|---|---|---|---|');
    for (const os of [1, 2]) for (const aa of [0, 1]) { const R = all.filter(r => (r.P.os || 2) === os && (r.P.aa === undefined ? 1 : r.P.aa) === aa); if (!R.length) continue;
      P(`| ${os} | ${aa} | ${R.length} | ${med(R, 'aliasDb')} | ${med(R, 'aliasConvDb')} | ${rate(R.filter(r => r.aliasConvClass === 'folding').length, R.length)} | ${rate(R.filter(r => r.aliasConvClass === 'dynamics').length, R.length)} |`); }
    P('');
    const dyn = all.filter(r => r.aliasConvClass === 'dynamics'), fbOn = r => r.P.fb > 0.0005 || r.P.xm > 0.0005;
    P(`Of the ${dyn.length} patches classed \`dynamics\`, ${rate(dyn.filter(fbOn).length, dyn.length)} have feedback or cross-member modulation on (in the whole run: ${rate(all.filter(fbOn).length, all.length)}).`);
    P('');
  }

  /* ---- CPU: the Crushed-bells class */
  P('## CPU by members × sounding blades — the Crushed-bells class (B313)');
  P('');
  P('Median `cpuVoiceNorm` (% of real time per voice) and the overload6 rate, all modes pooled. B313 measured Crushed bells at ~15-21% per voice and traced the cost to members × blades.');
  P('');
  P('| N | 0 blades | 1 blade | 2 blades |');
  P('|---|---|---|---|');
  for (let N = 1; N <= 9; N++) {
    const cells = [0, 1, 2].map(b => { const R = all.filter(r => r.P.N === N && r.blades === b); return R.length ? `${f(100 * pct(R.map(r => r.cpuVoiceNorm), 0.5), 1)}% · ${rate(R.filter(r => r.fail.includes('overload6')).length, R.length)} (n ${R.length})` : '—'; });
    P(`| ${N} | ${cells.join(' | ')} |`);
  }
  const ov = all.filter(r => r.fail.includes('overload6'));
  const cls = r => r.P.N >= 6 && r.blades === 2;
  P('');
  P(`Overload6 patches: ${ov.length} of ${all.length}; of those, ${rate(ov.filter(cls).length, ov.length)} are in the Crushed-bells class (N ≥ 6, both blades sounding), which is ${rate(all.filter(cls).length, all.length)} of all patches. ` +
    `Median cpuVoiceNorm inside the class ${f(100 * pct(all.filter(cls).map(r => r.cpuVoiceNorm), 0.5), 1)}% vs outside ${f(100 * pct(all.filter(r => !cls(r)).map(r => r.cpuVoiceNorm), 0.5), 1)}%.`);
  const preset = JSON.parse(readRepo('reference/scalpel/data/presets.json')).presets.find(p => p.name === 'Crushed bells');
  if (preset) {
    const pp = Object.assign({}, loadSpace().defaults, preset.params, { b1on: 1 });
    const m = measure(pp, 1);
    /* the machine's 1-minute load average beside the timing: honesty metadata, never an input */
    P(`Sentinel — the preset "Crushed bells" itself through the same measurement, in this (single) process: cpuVoice ${f(100 * m.cpuVoice, 1)}% per voice (× 6 voices = ${f(600 * m.cpuVoice, 0)}%), aliasDb ${f(m.aliasDb, 1)}, rootPresence ${f(m.rootPresence, 2)}` +
      ` (raw timing; 1-minute load average ${loadavg()[0].toFixed(1)} on ${cpus().length} cores when it was taken — re-timings of this preset in the authoring session read ~22% to ~70% per voice as the load moved; B313 measured 15–21%).`);
  }
  P('');
  P('Top 12 by cpuVoiceNorm:');
  P('');
  P('| mode#i | cpuVoiceNorm | N | blades | mode / mode2 | os | dcMode | b2mix | kRule |');
  P('|---|---|---|---|---|---|---|---|---|');
  for (const r of all.slice().sort((a, b) => b.cpuVoiceNorm - a.cpuVoiceNorm).slice(0, 12))
    P(`| ${r.mode}#${r.i} | ${f(100 * r.cpuVoiceNorm, 1)}% | ${r.P.N} | ${r.blades} | ${r.P.mode} / ${r.P.b2on ? r.P.mode2 : '-'} | ${r.P.os} | ${r.P.dcMode} | ${f(r.P.b2mix, 2)} | ${r.P.kRule} |`);
  P('');

  /* ---- hotspots: lifts per parameter bin */
  const binOf = (p, v) => (p.kind === 'c' ? 'q' + Math.min(4, Math.floor(posOf(p, v) * 5)) : String(v));
  const binsFor = p => { const m = new Map(); for (const r of all) { if (!evalCond(T.params[p.key].active_when, r.P, T.predicates)) continue; const b = binOf(p, r.P[p.key]); (m.get(b) || m.set(b, []).get(b)).push(r); } return m; };
  const BINS = new Map(params.filter(p => p.kind !== 's').map(p => [p.key, binsFor(p)]));
  P('## Failure and label hotspots (lift = rate in the bin ÷ rate overall; bins with n ≥ 25; continuous rows by taper quintile q0..q4; `noisy`/`rough` are B360 LABELS, not failures)');
  P('');
  for (const c of CLASSES.concat(INCO).concat(LABELS)) {
    const has = r => r.fail.includes(c) || r.inco.includes(c) || r.labels.includes(c), base = all.filter(has).length / all.length;
    if (!base) { P(`- **${c}**: none in ${all.length} patches.`); continue; }
    const lifts = [];
    for (const [k, m] of BINS) for (const [b, R] of m) if (R.length >= 25) { const rr = R.filter(has).length / R.length; lifts.push([k + '=' + b, rr, R.length]); }
    lifts.sort((a, b) => b[1] - a[1]);
    P(`- **${c}** (overall ${rate(all.filter(has).length, all.length)}): ` + lifts.slice(0, 8).map(([kb, rr, n]) => `\`${kb}\` ${(100 * rr).toFixed(0)}% (×${(rr / base).toFixed(1)}, n ${n})`).join(' · '));
  }
  P('');
  const nf = all.filter(r => r.fail.includes('nonfinite'));
  if (nf.length) { P(`Non-finite patches (re-derive with samplePatch(seed, i, mode)): ${nf.slice(0, 20).map(r => r.mode + '#' + r.i).join(', ')}${nf.length > 20 ? ' …' : ''}`); P(''); }

  /* ---- key pairs */
  P('## Key pairs');
  P('');
  /* a value the tree says is INACTIVE in that patch is its default, not a choice: binned as "off" */
  const lab = (r, k) => (evalCond(T.params[k].active_when, r.P, T.predicates) ? r.P[k] : 'off');
  const order = (x, y) => (x === 'off' ? 1 : y === 'off' ? -1 : x - y);
  const pair = (ka, kb, metric, d, fmt) => {
    const va = [...new Set(all.map(r => lab(r, ka)))].sort(order), vb = [...new Set(all.map(r => lab(r, kb)))].sort(order);
    P(`**${ka} × ${kb}** — ${metric === 'fail' ? 'healthy yield' : 'median ' + metric} (n); "off" = inactive per the tree in that patch:`);
    P('');
    P(`| ${ka} \\ ${kb} | ` + vb.join(' | ') + ' |');
    P('|---|' + vb.map(() => '---').join('|') + '|');
    for (const a of va) P(`| ${a} | ` + vb.map(b => { const R = all.filter(r => lab(r, ka) === a && lab(r, kb) === b); if (R.length < 5) return R.length ? `(n ${R.length})` : '—';
      return metric === 'fail' ? `${rate(R.filter(r => !r.fail.length).length, R.length)} (${R.length})` : `${fmt(pct(R.map(r => r[metric]).filter(Number.isFinite), 0.5))} (${R.length})`; }).join(' | ') + ' |');
    P('');
  };
  pair('mode', 'mode2', 'fail');
  pair('mode', 'mode2', 'aliasDb', 1, x => f(x, 1));
  pair('os', 'aa', 'aliasDb', 1, x => f(x, 1));
  pair('dcMode', 'b2on', 'dcRatio', 4, x => f(x, 4));
  pair('law', 'kRule', 'roughness', 4, x => f(x, 4));
  pair('N', 'b2on', 'cpuVoiceNorm', 3, x => f(100 * x, 1) + '%');

  /* ---- per-parameter */
  P('## Per parameter');
  P('');
  P('Live = how often the tree left it live (sampled); then the any-failure rate and the median aliasDb per bin (enum option / taper quintile), for bins with n ≥ 25.');
  P('');
  P('| param | live | failure rate by bin | median aliasDb by bin |');
  P('|---|---|---|---|');
  const anyFail = r => r.fail.length > 0;
  for (const p of params) {
    if (p.kind === 's') continue;
    const m = BINS.get(p.key), live = [...m.values()].reduce((a, R) => a + R.length, 0);
    const bins = [...m.entries()].filter(([, R]) => R.length >= 25).sort((a, b) => (a[0] < b[0] ? -1 : 1));
    P(`| ${p.key} | ${rate(live, all.length)} | ${bins.map(([b, R]) => `${b}:${(100 * R.filter(anyFail).length / R.length).toFixed(0)}%`).join(' ') || '—'} | ${bins.map(([b, R]) => `${b}:${f(pct(R.map(r => r.aliasDb), 0.5), 0)}`).join(' ') || '—'} |`);
  }
  P('');
  P('## Open questions for P4 / P5');
  P('');
  P('- The thresholds above are provisional; the blind listening pass fitted `alias` and `rootAbsent` (gates) and `rough`/`noisy` (B360: LABELS, not gates) — P4 still fits distributions to all four.');
  P('- `overload6` is a JS-reference cost (B313: "a limit of the JS reference, not a verdict on the C++ port"). Should P4 bound N × blades by the JS cost, or wait for a C++ cost table?');
  P('- The aliasing reference is the engine\'s own 4× oversampling, whose blade caps move with it (gauntlet.mjs header): a cap-free reference needs the caps separated from `os` in the engine, which is out of this tool\'s reach.');
  P('- B351: the `alias` class reads `aliasConvDb` (the os-convergence estimator) at a cut re-fitted on the v2 ratings; `aliasDb` is a measured column. A run without the estimator\'s fields (before B346) is refused by gauntlet.mjs failures().');
  P('- `rough` counts a detuned swarm\'s own beating (Sethares roughness is fast beating, which is what a supersaw is). Should "discordance" for the random button exclude beating between members of one partial (e.g. measure roughness on a de-detuned render) or keep it?');
  P('- The harmonic detune law (`h.law` 4, `harmReach`) is the top `alias` and `noisy` hotspot: at E5 its upper members can sit near or above Nyquist. Is that a range to bound in P4, or a law to clamp in the engine?');
  P('- Edge-mode `silent` is mostly `gain` 0 and similar trivial extremes. Should P5\'s FUZZ mode exclude known-silent corners, or keep them as sanity cases?');
  const md = L.join('\n') + '\n';
  mkdirSync(dirname(join(ROOT, out)), { recursive: true });
  writeFileSync(join(ROOT, out), md);
  console.error(`gauntlet report: ${all.length} patches → ${out}`);
}

if (process.argv[1] && process.argv[1].endsWith('gauntlet_report.mjs')) await report();
