/*
 * bank_check — the factory bank is loadable, self-consistent, audible, and still
 * demonstrates the coupling laws it claims to (B130). Standalone; NOT wired into
 * ./verify (the standing ruling: wiring a gate is the human's decision).
 *
 *   bank_check <bank-dir>          (e.g. docs/presets/factory)
 *
 * Deliberately reads the SHIPPED FILES and never the generator's table: a check
 * that consulted `gen_factory_bank.cpp` would certify the table, not the bank.
 * The only thing hard-coded here is the acceptance contract itself — the eight
 * category names, the size band, the four named exemplars and the nine FX types.
 *
 * Per file:
 *   A  applies (hypersaw_debug_apply)
 *   B  re-saves BIT-IDENTICAL to what is on disk (statefix's assertion, in the
 *      JSON transport). CALIBRATED: the same comparison against a patch with one
 *      planted parameter change must FAIL, or the comparison is blind.
 *   C  makes sound: 2 s of a C4 strike, RMS above -60 dBFS, peak under 0 dBFS,
 *      no NaN/Inf anywhere.
 *   D  every cornerNames entry is "" or a corner preset that ships in corners/,
 *      and the named corner MATCHES the shipped file (cornerMatches — the same
 *      call the GUI's edited-since-load asterisk makes).
 *
 * Exemplars, each through hypersaw_debug_viz — the same R / RA / RB the GUI's
 * phase circle draws:
 *   demo/MISC - Cloud To Lock Sweep        K 1 -> R past 0.9 within 2 s of a strike;
 *                                   K 0 -> R stays under 0.3
 *   demo/MISC - Consonance Gravity Chord   C4 + G4 settle within +/-1 cent of 3/2 by
 *                                   3 s; with Gravity at 0 they must NOT.
 *                                   MEASURED CORRECTION to B130's wording: the
 *                                   equal-tempered fifth is 1.96 c NARROW of
 *                                   3/2, not sharp (the control reads -1.960 c
 *                                   against the closed-form 1200*log2(1.5) =
 *                                   701.955 vs 700). Same magnitude, opposite
 *                                   sign; the assertion is |error| either way.
 *   demo/MISC - Splay Interference         K -1 -> R under 0.1; the same patch at K +1
 *                                   must read R over 0.9 (the probe can see
 *                                   coherence, so a zero means splay and not a
 *                                   dead meter)
 *   morph/MO - Quantum Morph             the four corners' (R, RA, RB) signatures
 *                                   differ pairwise by >= 0.4
 *   fx (every category)             every FX module the rack ships today (types
 *                                   1..9) is used by at least one patch
 *
 * KNOWN LIMIT, stated rather than hidden: the splay exemplar's "even lattice,
 * gap 1/n" is asserted through its scalar consequence (R -> 0 with a calibrated
 * positive control), not by reading the phases — hypersaw_debug_viz publishes
 * the order parameters, not the phase array, and B130 fixes that signature.
 * R near zero is necessary for an even lattice, not sufficient.
 */

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>
#include <vector>

#include <clap/clap.h>
#include "../src/hypersaw_clap_entry.h"

extern "C" bool hypersaw_debug_apply(const clap_plugin_t *, const char *);
extern "C" void hypersaw_debug_state(const clap_plugin_t *, char *, uint32_t);
extern "C" bool hypersaw_debug_cornermatches(const clap_plugin_t *, int, const char *);
extern "C" void hypersaw_debug_voices(const clap_plugin_t *, char *, uint32_t);
extern "C" void hypersaw_debug_viz(const clap_plugin_t *, int, double *, double *, double *, int *, double *);
extern "C" int hypersaw_debug_phases(const clap_plugin_t *, int, double *, int);

namespace fs = std::filesystem;

namespace
{
#include "notefuzz_scaffold.inc"

int g_fail = 0;
void check(bool ok, const std::string &what)
{
  std::printf("%s %s\n", ok ? "OK  " : "FAIL", what.c_str());
  if (!ok) g_fail++;
}

/* The state header's `build` key is provenance — written, never read back
   (hypersaw_clap.cpp, the B100 header comment). A re-save therefore stamps the
   CURRENT build, so comparing it would assert "the bank was generated by this
   exact commit", which is a gate that fails on the next commit for no musical
   reason. Everything else in the blob is compared byte for byte. */
std::string dropBuild(std::string s)
{
  const size_t at = s.find("\"build\":\"");
  if (at == std::string::npos) return s;
  const size_t end = s.find('"', at + 9);
  if (end == std::string::npos) return s;
  return s.erase(at, end + 1 - at + (end + 1 < s.size() && s[end + 1] == ',' ? 1 : 0));
}

std::string readAll(const fs::path &p)
{
  std::ifstream f(p, std::ios::binary);
  std::stringstream ss;
  ss << f.rdbuf();
  return ss.str();
}

/* cornerNames out of a patch blob: four JSON strings, the shell's own escape. */
std::vector<std::string> cornerNamesOf(const std::string &json)
{
  std::vector<std::string> out;
  const size_t np = json.find("\"cornerNames\"");
  if (np == std::string::npos) return out;
  const char *c = std::strchr(json.c_str() + np + 13, '[');
  for (int k = 0; c && k < 4; k++)
  {
    const char *q = std::strchr(c + 1, '"');
    if (!q) break;
    std::string v;
    const char *e = q + 1;
    for (; *e && *e != '"'; e++)
    {
      if (*e == '\\' && e[1]) { v += e[1]; e++; }
      else v += *e;
    }
    out.push_back(v);
    const char *nx = std::strchr(e, ',');
    const char *cl = std::strchr(e, ']');
    if (!nx || (cl && cl < nx)) break;
    c = nx;
  }
  return out;
}

double jsonNumber(const std::string &json, const std::string &key, double dflt)
{
  const std::string needle = "\"" + key + "\":";
  const size_t at = json.find(needle);
  return at == std::string::npos ? dflt : std::strtod(json.c_str() + at + needle.size(), nullptr);
}

/* ---- rig --------------------------------------------------------------- */

struct Rig
{
  const clap_plugin_t *p = nullptr;
  std::vector<float> L, R;
  clap_audio_buffer_t out{};
  clap_process_t proc{};
  float *ch[2];
  double peak = 0, sumSq = 0;
  size_t nSamp = 0;
  bool dirty = false;   // NaN or Inf seen

  void boot()
  {
    auto *f = (const clap_plugin_factory_t *)hypersaw_entry_get_factory(CLAP_PLUGIN_FACTORY_ID);
    p = f->create_plugin(f, &kHost, "com.lifted-truck.hypersaw");
    p->init(p);
    p->activate(p, kSR, 32, kBlock);
    p->start_processing(p);
    L.assign(kBlock, 0);
    R.assign(kBlock, 0);
    ch[0] = L.data();
    ch[1] = R.data();
    out.data32 = ch;
    out.channel_count = 2;
    proc.frames_count = kBlock;
    proc.audio_outputs = &out;
    proc.audio_outputs_count = 1;
    proc.out_events = &kOut;
  }
  void step(EvList &e)
  {
    e.finalize();
    proc.in_events = &e.list;
    p->process(p, &proc);
    for (int i = 0; i < kBlock; i++)
      for (float v : {L[i], R[i]})
      {
        if (!std::isfinite(v)) { dirty = true; continue; }
        peak = std::max(peak, (double)std::fabs(v));
        sumSq += (double)v * v;
        nSamp++;
      }
  }
  void run(double sec) { for (int i = 0; i < Math_blocks(sec); i++) { EvList e; step(e); } }
  void params(const std::vector<std::pair<clap_id, double>> &pv)
  {
    EvList e;
    for (const auto &q : pv) e.params.push_back(mkParam(q.first, q.second));
    step(e);
  }
  void note(int key, bool on, int id)
  {
    EvList e;
    e.notes.push_back(mkNote(on ? CLAP_EVENT_NOTE_ON : CLAP_EVENT_NOTE_OFF, 0, (int16_t)key, id,
                             on ? 0.9 : 0));
    step(e);
  }
  bool load(const std::string &json)
  {
    const bool ok = hypersaw_debug_apply(p, json.c_str());
    run(0.05);   // the apply is QUEUED; process() is what drains it
    return ok;
  }
  double R0() const { double r, a, b, rn; int n; hypersaw_debug_viz(p, 0, &r, &a, &b, &n, &rn); return r; }
  double RN0() const { double r, a, b, rn; int n; hypersaw_debug_viz(p, 0, &r, &a, &b, &n, &rn); return rn; }
  void viz(double &r, double &a, double &b, double &rn, int &n) const { hypersaw_debug_viz(p, 0, &r, &a, &b, &n, &rn); }
  /* Gap uniformity U = 1 - std(gap)/mean(gap) over the sorted phase gaps:
     an even lattice reads ~1, a lock ~0 (one big gap, the rest ~0), a cloud
     in between. The discriminator RN cannot be (B131). */
  double gapU() const { double ph[64]; const int n = hypersaw_debug_phases(p, 0, ph, 64); if (n < 2) return 0;
    std::vector<double> v(ph, ph + n); for (double &x : v) x = x - std::floor(x); std::sort(v.begin(), v.end());
    double mean = 1.0 / n, var = 0; for (int i = 0; i < n; i++) { const double g = (i + 1 < n ? v[i + 1] : v[0] + 1.0) - v[i]; var += (g - mean) * (g - mean); }
    const double sd = std::sqrt(var / n); return std::max(0.0, 1.0 - sd / mean); }
  double rmsDb() const
  {
    if (!nSamp) return -999;
    const double r = std::sqrt(sumSq / (double)nSamp);
    return r > 0 ? 20 * std::log10(r) : -999;
  }
  void kill() { p->stop_processing(p); p->deactivate(p); p->destroy(p); }
};

std::string saveState(const clap_plugin_t *p)
{
  static char buf[1 << 18];
  hypersaw_debug_state(p, buf, sizeof buf);
  return buf;
}

/* Strike C4 and follow R for `sec`, returning the peak R and the time it first
   crossed `want` (or -1). The swarm is sampled once per block, which is the
   same cadence publishViz feeds the GUI at. */
struct RTrace
{
  double peakR = 0, lateMaxR = 0, lateMinR = 1, lateMeanR = 0;
  double lateMinRN = 1, lateMinU = 1;   // B131: lattice observables' floors in the late window
  double tCross = -1;
  long lateN = 0;
};
RTrace strikeAndFollow(Rig &r, double sec, double want, double lateFrom)
{
  RTrace t;
  r.note(60, true, 1);
  const int blocks = Math_blocks(sec);
  for (int i = 0; i < blocks; i++)
  {
    EvList e;
    r.step(e);
    const double now = (double)(i + 1) * kBlock / kSR;
    const double R = r.R0();
    t.peakR = std::max(t.peakR, R);
    if (now >= lateFrom)
    {
      t.lateMaxR = std::max(t.lateMaxR, R);
      t.lateMinR = std::min(t.lateMinR, R);
      t.lateMinRN = std::min(t.lateMinRN, r.RN0());
      t.lateMinU = std::min(t.lateMinU, r.gapU());
      t.lateMeanR += R;
      t.lateN++;
    }
    if (t.tCross < 0 && R >= want) t.tCross = now;
  }
  if (t.lateN) t.lateMeanR /= (double)t.lateN;
  return t;
}

/* The two gated notes' current fundamentals, as the gravity law leaves them. */
bool twoVoiceRatio(Rig &r, double &ratio)
{
  char b[1024];
  hypersaw_debug_voices(r.p, b, sizeof b);
  std::vector<double> f;
  for (char *tok = std::strtok(b, ";"); tok; tok = std::strtok(nullptr, ";"))
  {
    int slot = 0, midi = 0, gate = 0, glide = 0;
    double f0 = 0, f0cur = 0, tune = 0;
    if (std::sscanf(tok, "%d,%d,%d,%lf,%lf,%d,%lf", &slot, &midi, &gate, &f0, &f0cur, &glide,
                    &tune) == 7 && gate)
      f.push_back(f0cur);
  }
  if (f.size() != 2) return false;
  std::sort(f.begin(), f.end());
  ratio = f[1] / f[0];
  return true;
}

double centsFromJust(double ratio) { return 1200.0 * std::log2(ratio / 1.5); }

}  // namespace

int main(int argc, char **argv)
{
  if (argc < 2)
  {
    std::fprintf(stderr, "usage: bank_check <bank-dir>   (e.g. docs/presets/factory)\n");
    return 2;
  }
  const fs::path root = argv[1];
  const char *kCats[] = {"lead", "bass", "pad", "pluck", "keys", "fx", "morph", "demo"};

  // ---- inventory ------------------------------------------------------
  std::vector<fs::path> files;
  for (const char *c : kCats)
  {
    const fs::path dir = root / c;
    if (!fs::is_directory(dir)) continue;
    for (const auto &e : fs::directory_iterator(dir))
      if (e.path().extension() == ".json") files.push_back(e.path());
  }
  std::sort(files.begin(), files.end());
  std::printf("bank: %zu patches under %s\n", files.size(), root.string().c_str());
  check(files.size() >= 30 && files.size() <= 50,
        "bank holds 30..50 patches (" + std::to_string(files.size()) + ")");

  std::vector<std::string> cornerNames;
  if (fs::is_directory(root / "corners"))
    for (const auto &e : fs::directory_iterator(root / "corners"))
      if (e.path().extension() == ".json") cornerNames.push_back(e.path().stem().string());
  std::sort(cornerNames.begin(), cornerNames.end());
  check(!cornerNames.empty(), "corners/ ships at least one corner preset");

  // ---- per file -------------------------------------------------------
  bool fxSeen[10] = {false};
  bool calibrated = false;
  for (const auto &f : files)
  {
    const std::string tag = f.parent_path().filename().string() + "/" + f.stem().string();
    const std::string blob = readAll(f);

    Rig r;
    r.boot();
    const bool applied = r.load(blob);
    check(applied, tag + ": applies");
    if (!applied) { r.kill(); continue; }

    // B: bit-identical re-save (build stamp excepted — see dropBuild)
    const std::string again = saveState(r.p);
    const bool same = dropBuild(again) == dropBuild(blob);
    check(same, tag + ": re-save is bit-identical to the file");
    if (!same)
    {
      const std::string a = dropBuild(blob), b = dropBuild(again);
      size_t i = 0;
      while (i < a.size() && i < b.size() && a[i] == b[i]) i++;
      std::printf("     first difference at byte %zu:\n       file  ...%s\n       resave...%s\n", i,
                  a.substr(i > 40 ? i - 40 : 0, 110).c_str(),
                  b.substr(i > 40 ? i - 40 : 0, 110).c_str());
    }

    // B-calibration, once: the same comparison must FAIL on a planted change.
    if (!calibrated && same)
    {
      calibrated = true;
      Rig c;
      c.boot();
      const double mv = jsonNumber(blob, "masterVol", 1.0);
      c.load(blob);
      c.params({{100, mv > 0.6 ? 0.3 : 0.9}});
      c.run(0.02);
      check(dropBuild(saveState(c.p)) != dropBuild(blob),
            "CONTROL: a planted masterVol change makes the re-save comparison FAIL");
      c.kill();
    }

    // C: it makes sound
    r.peak = 0; r.sumSq = 0; r.nSamp = 0; r.dirty = false;
    r.note(60, true, 1);
    r.run(2.0);
    const double db = r.rmsDb();
    check(!r.dirty, tag + ": no NaN/Inf in 2 s of C4");
    char msg[160];
    std::snprintf(msg, sizeof msg, "%s: RMS %.1f dBFS > -60, peak %.3f < 1.0", tag.c_str(), db,
                  r.peak);
    check(db > -60.0 && r.peak < 1.0, msg);

    // D: cornerNames name shipped corner presets, and the corners agree
    const std::vector<std::string> names = cornerNamesOf(blob);
    check(names.size() == 4, tag + ": carries cornerNames");
    check(blob.find("\"morphLayout\":2") != std::string::npos, tag + ": carries morphLayout 2");
    check(blob.find("\"schema\":3") != std::string::npos, tag + ": carries the state header");
    for (size_t k = 0; k < names.size(); k++)
    {
      if (names[k].empty()) continue;
      const fs::path cp = root / "corners" / (names[k] + ".json");
      const bool ships = fs::exists(cp);
      check(ships, tag + ": corner " + std::string(1, (char)('A' + k)) + " names a shipped preset '" +
                       names[k] + "'");
      if (!ships) continue;
      check(hypersaw_debug_cornermatches(r.p, (int)k, readAll(cp).c_str()),
            tag + ": corner " + std::string(1, (char)('A' + k)) + " matches corners/" + names[k]);
    }

    for (int slot = 1; slot <= 4; slot++)
    {
      char key[16];
      std::snprintf(key, sizeof key, "fx%dtype", slot);
      const int t = (int)jsonNumber(blob, key, 0);
      if (t > 0 && t < 10) fxSeen[t] = true;
    }
    r.kill();
  }
  check(calibrated, "the re-save comparison was calibrated on at least one file");

  // ---- every FX module the rack ships is demonstrated -----------------
  {
    const char *kFxNames[10] = {"Off",  "Drive", "Filter", "Gain", "Comp",
                               "Comb", "Notch", "Echo",   "Room", "Delay"};
    for (int t = 1; t <= 9; t++)
      check(fxSeen[t], std::string("FX type ") + kFxNames[t] + " is demonstrated by some patch");
  }

  // ---- exemplar: cloud-to-lock sweep ----------------------------------
  {
    const fs::path f = root / "demo" / "MISC - Cloud To Lock Sweep.json";
    check(fs::exists(f), "demo/MISC - Cloud To Lock Sweep ships");
    if (fs::exists(f))
    {
      const std::string blob = readAll(f);
      Rig lock;
      lock.boot();
      lock.load(blob);
      lock.params({{6, 1.0}});
      const RTrace t1 = strikeAndFollow(lock, 2.0, 0.9, 0.0);
      char m[200];
      std::snprintf(m, sizeof m, "cloud-to-lock: K 1 -> R crossed 0.9 at %.2f s (peak %.3f)",
                    t1.tCross, t1.peakR);
      check(t1.tCross >= 0 && t1.tCross <= 2.0, m);
      lock.kill();

      Rig cloud;
      cloud.boot();
      cloud.load(blob);
      cloud.params({{6, 0.0}});
      // The swarm is struck in phase, so R starts at 1 by construction and
      // falls as the voices drift; the claim is about the settled cloud, which
      // is why the window opens at 0.5 s.
      const RTrace t0 = strikeAndFollow(cloud, 2.0, 2.0, 0.5);
      /* The SETTLED order parameter, not an instantaneous bound. An uncoupled
         swarm of n voices does not sit at R = 0: its resultant is a random walk
         about 1/sqrt(n) whose instantaneous value is Rayleigh-distributed, so a
         max-based bound would be asserting a property finite-n Kuramoto does not
         have and would go red on an unlucky sample. The mean over the settled
         window IS the order parameter; the peak is printed so the fluctuation
         stays visible rather than hidden behind the average. */
      std::snprintf(m, sizeof m,
                    "cloud-to-lock: K 0 -> settled R under 0.3 (mean %.3f, min %.3f, peak %.3f)",
                    t0.lateMeanR, t0.lateMinR, t0.lateMaxR);
      check(t0.lateMeanR < 0.3, m);
      cloud.kill();
    }
  }

  // ---- exemplar: consonance-gravity chord -----------------------------
  {
    const fs::path f = root / "demo" / "MISC - Consonance Gravity Chord.json";
    check(fs::exists(f), "demo/MISC - Consonance Gravity Chord ships");
    if (fs::exists(f))
    {
      const std::string blob = readAll(f);
      double cOn = 99, cOff = 99, ratio = 0;
      Rig on;
      on.boot();
      on.load(blob);
      on.note(60, true, 1);
      on.note(67, true, 2);
      on.run(3.0);
      if (twoVoiceRatio(on, ratio)) cOn = centsFromJust(ratio);
      on.kill();

      Rig off;
      off.boot();
      off.load(blob);
      off.params({{29, 0.0}});   // Gravity off: the control
      off.note(60, true, 1);
      off.note(67, true, 2);
      off.run(3.0);
      if (twoVoiceRatio(off, ratio)) cOff = centsFromJust(ratio);
      off.kill();

      char m[200];
      std::snprintf(m, sizeof m, "gravity: C4+G4 settle to %+.3f c from 3/2 by 3 s (|.| <= 1)", cOn);
      check(std::fabs(cOn) <= 1.0, m);
      std::snprintf(m, sizeof m,
                    "CONTROL: with Gravity 0 the same fifth stays tempered at %+.3f c", cOff);
      check(std::fabs(cOff) > 1.0, m);
    }
  }

  // ---- exemplar: splay interference -----------------------------------
  {
    const fs::path f = root / "demo" / "MISC - Splay Interference.json";
    check(fs::exists(f), "demo/MISC - Splay Interference ships");
    if (fs::exists(f))
    {
      const std::string blob = readAll(f);
      Rig sp;
      sp.boot();
      sp.load(blob);
      const RTrace t = strikeAndFollow(sp, 2.0, 2.0, 1.0);
      char m[200];
      std::snprintf(m, sizeof m,
                    "splay: K -1 -> R under 0.1 after 1 s (max %.4f, mean %.4f)", t.lateMaxR,
                    t.lateMeanR);
      check(t.lateMaxR < 0.1, m);
      // B131: the lattice asserted DIRECTLY — an even splay has RN = 1, a cloud ~1/sqrt(n)
      std::printf("     splay lattice: RN min %.3f, gap uniformity U min %.3f\n", t.lateMinRN, t.lateMinU);
      // B131: the lattice asserted DIRECTLY through gap uniformity (an even
      // lattice ~0.8 here; a cloud ~0.1; a lock 0). RN cannot do this job: a
      // lock's finite phase spread scatters e^{i n theta} (measured 0.21).
      std::snprintf(m, sizeof m, "splay: the lattice's gap uniformity stays over 0.7 through the late window (min %.3f)", t.lateMinU);
      check(t.lateMinU > 0.7, m);
      sp.kill();

      Rig pos;
      pos.boot();
      pos.load(blob);
      pos.params({{6, 1.0}});
      const RTrace tp = strikeAndFollow(pos, 2.0, 0.9, 1.0);
      std::snprintf(m, sizeof m,
                    "CONTROL: the same patch at K +1 reads R over 0.9 (max %.3f) — the meter is "
                    "not dead",
                    tp.lateMaxR);
      check(tp.lateMaxR > 0.9, m);
      pos.kill();
    }
  }

  // ---- exemplar: quantum morph ----------------------------------------
  {
    const fs::path f = root / "morph" / "MO - Quantum Morph.json";
    check(fs::exists(f), "morph/MO - Quantum Morph ships");
    if (fs::exists(f))
    {
      const std::string blob = readAll(f);
      // A=(0,0) B=(1,0) C=(0,1) D=(1,1) — MorphCore::weights
      const double xy[4][2] = {{0, 0}, {1, 0}, {0, 1}, {1, 1}};
      const char *lbl[4] = {"A cloud", "B lock", "C splay", "D two-cluster"};
      double sig[4][4] = {{0}};   // R, RA, RB, RN (B131: RN separates a cloud from a splay)
      for (int k = 0; k < 4; k++)
      {
        Rig r;
        r.boot();
        r.load(blob);
        r.params({{152, xy[k][0]}, {153, xy[k][1]}});
        r.run(0.3);
        r.note(60, true, 1);
        r.run(1.0);   // past the strike transient; the corner has settled
        /* The signature is the MEAN of each order parameter over a 2 s
           window, not one instantaneous sample: at finite n every one of these
           is a fluctuating quantity, and a single sample would make the
           pairwise-separation assertion a coin toss on an unlucky block.
           min/max are printed so the fluctuation stays visible. */
        double lo[4] = {1, 1, 1, 1}, hi[4] = {0, 0, 0, 0};
        int n = 0;
        long m = 0;
        for (int i = 0; i < Math_blocks(2.0); i++)
        {
          EvList e;
          r.step(e);
          double v[4], rn;
          r.viz(v[0], v[1], v[2], rn, n);
          v[3] = r.gapU();
          for (int c = 0; c < 4; c++)
          {
            sig[k][c] += v[c];
            lo[c] = std::min(lo[c], v[c]);
            hi[c] = std::max(hi[c], v[c]);
          }
          m++;
        }
        for (int c = 0; c < 4; c++) sig[k][c] /= (double)(m ? m : 1);
        std::printf("     corner %-14s R %.3f [%.3f..%.3f]  RA %.3f  RB %.3f  U %.3f [%.3f..%.3f]  (n %d)\n", lbl[k],
                    sig[k][0], lo[0], hi[0], sig[k][1], sig[k][2], sig[k][3], lo[3], hi[3], n);
        r.kill();
      }
      for (int a = 0; a < 4; a++)
        for (int b = a + 1; b < 4; b++)
        {
          double d = 0;
          for (int c = 0; c < 4; c++) d = std::max(d, std::fabs(sig[a][c] - sig[b][c]));
          char m[160];
          std::snprintf(m, sizeof m, "quantum-morph: %s vs %s differ by %.3f (>= 0.4)", lbl[a],
                        lbl[b], d);
          check(d >= 0.4, m);
        }
    }
  }

  hypersaw_entry_deinit();
  std::printf("bank_check: %d failure(s)\n", g_fail);
  return g_fail ? 1 : 0;
}
