#!/usr/bin/env python3
"""Byte-array embeds for build-time resources. Two modes:

  embed_file.py <input> <output.h> <symbol>
      one file (the GUI HTML). Hex array rather than a raw string literal so
      the content can never collide with a delimiter or hit MSVC's
      string-length cap.

  embed_file.py --bank <dir> <output.h> <symbol>
      every *.json under <dir>, recursively, as one hypersaw::FactoryFile
      array plus a <symbol>_version string (B129). The version is a digest of
      the bank's own contents, so adding or editing a preset bumps it without
      anyone remembering to; the install path uses it to decide whether the
      bank on disk is already current. An EMPTY or ABSENT <dir> is legal and
      yields a zero-length array — the bank content lands separately (B130)
      and the build must not depend on it existing.
"""
import hashlib
import os
import sys


def emit_bytes(f, sym, data):
    f.write(f"static const unsigned char {sym}[] = {{\n")
    for i in range(0, len(data), 24):
        f.write("  " + ",".join(str(b) for b in data[i:i + 24]) + ",\n")
    f.write("};\n")


def single(src, dst, sym):
    data = open(src, "rb").read()
    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write("// generated by tools/embed_file.py — do not edit\n#pragma once\n#include <cstddef>\n")
        emit_bytes(f, sym + "_data", data)
        f.write(f"static const size_t {sym}_size = {len(data)};\n")


def bank(root, dst, sym):
    # Sorted so the generated header — and therefore the version digest — is a
    # function of the CONTENT alone, never of directory-walk order.
    files = []
    for dirpath, _dirnames, filenames in os.walk(root):
        for fn in sorted(filenames):
            if fn.endswith(".json"):
                full = os.path.join(dirpath, fn)
                rel = os.path.relpath(full, root).replace(os.sep, "/")
                files.append((rel, full))
    files.sort()

    digest = hashlib.sha256()
    entries = []
    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write("// generated by tools/embed_file.py --bank — do not edit\n#pragma once\n")
        f.write('#include <cstddef>\n#include "gui/preset_store.h"\n')
        for i, (rel, full) in enumerate(files):
            data = open(full, "rb").read()
            digest.update(rel.encode("utf-8"))
            digest.update(b"\0")
            digest.update(str(len(data)).encode("ascii"))
            digest.update(b"\0")
            digest.update(data)
            category, _, name = rel.rpartition("/")
            name = name[:-len(".json")]
            emit_bytes(f, f"{sym}_b{i}", data)
            entries.append((category, name, f"{sym}_b{i}", len(data)))
        f.write(f"static const hypersaw::FactoryFile {sym}[] = {{\n")
        for category, name, symbol, size in entries:
            # C++ forbids a zero-length array; a dummy keeps the empty bank
            # compiling, and _count 0 keeps it inert.
            f.write(f'  {{"{category}", "{name}", {symbol}, {size}}},\n')
        if not entries:
            f.write('  {"", "", nullptr, 0},\n')
        f.write("};\n")
        f.write(f"static const size_t {sym}_count = {len(entries)};\n")
        f.write(f'static const char {sym}_version[] = "{digest.hexdigest()[:16]}";\n')


if __name__ == "__main__":
    if sys.argv[1] == "--bank":
        bank(sys.argv[2], sys.argv[3], sys.argv[4])
    else:
        single(sys.argv[1], sys.argv[2], sys.argv[3])
